apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout format raw local0

    defaults
        mode http
        timeout connect 5s
        timeout client  50s
        timeout server  50s

    frontend http_front
        bind *:8080
        default_backend web_backends

    backend web_backends
        server bintang httpbin.org:80
        server pandu java-openshift-jenkins-panduass-dev.apps.rm1.0a51.p1.openshiftapps.com:80
        server fayad java-openshift-jenkins-rmuhammadfayyadh-dev.apps.rm1.0a51.p1.openshiftapps.com:80
        server najah java-openshift-jenkins-sayyidatun-dev.apps.rm1.0a51.p1.openshiftapps.com:80
        server hilda java-openshift-jenkins-hildamathilda7-dev.apps.rm1.0a51.p1.openshiftapps.com:80


    resolvers mydns
        nameserver dns1 8.8.8.8:53
        hold valid 10s
